### ISSUE TITLE
Error while parsing user current config

### ISSUE THREAD

**Issue by mvehar** [shalvah/upgrader#1]
Trying to get property 'value' of non-object

  at vendor/shalvah/upgrader/src/Upgrader.php:163
    159▕         // Loop over the old config
    160▕         // TODO handle cases of mixed assoc- and list array
    161▕         foreach ($userCurrentConfig as $arrayItem) {
    162▕             // @phpstan-ignore-next-line Not yet sure how to handle mixed
  ➜ 163▕             $key = $arrayItem->key->value;

Error happens while using latest version of knuckleswtf/scribe in Laravel 8

**Comment by mvehar** [comment]
Issue is with the scribe package. Closing this one.

**Comment by shalvah** [comment]
So did you solve it?
